# Written by Grigori Fursin

alias: demo-ml-model-abtf-cognata-pytorch-training
uid: 49c05ac0d0454373

automation_alias: script
automation_uid: 5b4e0237da074764

private: true

category: Tests

tags:
- demo
- abtf
- ssd-resnet50
- cognata
- pytorch
- training

input_mapping:
  config: CM_ABTF_ML_MODEL_CONFIG
  dataset: CM_ABTF_DATASET
  nproc_per_node: CM_ABTF_ML_MODEL_TRAINING_NPROC_PER_NODE
  batch_size: CM_ABTF_ML_MODEL_TRAINING_BATCH_SIZE
  torch_distributed_type: CM_ABTF_ML_MODEL_TRAINING_DISTRIBUTED_TYPE
  torch_distributed_init: CM_ABTF_ML_MODEL_TRAINING_DISTRIBUTED_INIT
  dataset_folders: CM_ABTF_ML_MODEL_TRAINING_COGNATA_FOLDERS
  dataset_cameras: CM_ABTF_ML_MODEL_TRAINING_COGNATA_CAMERAS
  pretrained_model: CM_ABTF_ML_MODEL_TRAINING_PRETRAINED_PATH

default_env:
  CM_ABTF_ML_MODEL_CONFIG: baseline_8MP
  CM_ABTF_ML_MODEL_NAME: ssd
  CM_ABTF_DATASET: Cognata
  CM_ABTF_ML_MODEL_TRAINING_NPROC_PER_NODE: 1
  CM_ABTF_ML_MODEL_TRAINING_BATCH_SIZE: 1
  CM_ABTF_ML_MODEL_TRAINING_STORAGE: trained_models
  CM_ABTF_ML_MODEL_EPOCH: 2
  CM_ABTF_ML_MODEL_TRAINING_DISTRIBUTED_TYPE: nccl
  CM_ABTF_ML_MODEL_TRAINING_DISTRIBUTED_INIT: 'env://'

deps:

- tags: detect,os

- tags: get,python3
  names:
  - python
  - python3

########################################################################
- tags: get,generic-python-lib,_numpy
- tags: get,generic-python-lib,_package.typing-extensions
- tags: get,generic-python-lib,_package.sympy
- tags: get,generic-python-lib,_package.Pillow
- tags: get,generic-python-lib,_opencv-python

- tags: get,generic-python-lib,_package.Cython
- tags: get,generic-python-lib,_package.scikit-image
- tags: get,generic-python-lib,_package.torchmetrics
- tags: get,generic-python-lib,_package.torchinfo
- tags: get,generic-python-lib,_package.tensorboard
- tags: get,generic-python-lib,_package.tqdm
- tags: get,generic-python-lib,_package.pycocotools
- tags: get,generic-python-lib,_nvidia-apex

########################################################################
- tags: get,dataset,raw,mlcommons-cognata
  names:
  - raw-dataset-mlcommons-cognata

########################################################################
# Install PyTorch for CPU or CUDA

- enable_if_env:
    CM_DEVICE:
    - cpu
  tags: get,generic-python-lib,_torch
  names:
  - torch

- enable_if_env:
    CM_DEVICE:
    - cpu
  tags: get,generic-python-lib,_torchvision
  names:
  - torchvision

# CUDA

- enable_if_env:
    CM_DEVICE:
    - cuda
  tags: get,generic-python-lib,_torch_cuda
  names:
  - torch

- enable_if_env:
    CM_DEVICE:
    - cuda
  tags: get,generic-python-lib,_torchvision_cuda
  names:
  - torchvision


- tags: get,ml-model,abtf-ssd-pytorch
  names:
  - ml-model



############################################################
variations:
  cpu:
    group: device
    default: True
    env:
      CM_DEVICE: cpu

  cuda:
    docker:
      all_gpus: 'yes'
      base_image: nvcr.io/nvidia/pytorch:24.03-py3
    group:
      device
    env:
      CM_DEVICE: cuda
